version: '3.8'

# ASAgents Platform - Simple Production Deployment
# Express + SQLite backend with simple frontend

services:
  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - HOST=0.0.0.0
      - DATABASE_PATH=/app/data/database.sqlite
    volumes:
      - ./backend/data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - asagents-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Simple Frontend Server
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.simple.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - asagents-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  asagents-network:
    driver: bridge
